COHERE_API_KEY = "WpCTUcy541xUJFt2GpA0r5zrtVVD6IkvFtnz97UY"

QDRANT_HOST = "https://046843ec-e71e-4ab6-9100-711d8c1ee55b.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "u-g6fMdlAHQzNEH16uAZrkB1Fw1N4W9pqLwqrXJYwAWRsk2aHCzn3w" 

